

rggZZ SYST &
rggZZ NOMINAL &
rggZZ EG_RESOLUTION_ALL__1down &
rggZZ EG_RESOLUTION_ALL__1up &
rggZZ EG_SCALE_AF2__1down &
rggZZ EG_SCALE_AF2__1up &
rggZZ EG_SCALE_ALL__1down &
rggZZ EG_SCALE_ALL__1up &
rggZZ JET_EtaIntercalibration_NonClosure__1up &
rggZZ JET_EtaIntercalibration_NonClosure__1down &
rggZZ JET_GroupedNP_1__1up &
rggZZ JET_GroupedNP_1__1down &
rggZZ JET_GroupedNP_2__1up &
rggZZ JET_GroupedNP_2__1down &
rggZZ JET_GroupedNP_3__1up &
rggZZ JET_GroupedNP_3__1down &
rggZZ JET_JER_SINGLE_NP__1up &
rggZZ MET_SoftTrk_ResoPara &
rggZZ MET_SoftTrk_ResoPerp &
rggZZ MET_SoftTrk_ScaleDown &
rggZZ MET_SoftTrk_ScaleUp &
rggZZ MUON_ID__1down &
rggZZ MUON_ID__1up &
rggZZ MUON_MS__1down &
rggZZ MUON_MS__1up &
rggZZ MUON_SAGITTA_RESBIAS__1down &
rggZZ MUON_SAGITTA_RESBIAS__1up &
rggZZ MUON_SAGITTA_RHO__1down &
rggZZ MUON_SAGITTA_RHO__1up &
rggZZ MUON_SCALE__1down &
rggZZ MUON_SCALE__1up &
rggZZ PRW_DATASF__1down &
rggZZ PRW_DATASF__1up &
